# Generated by Django 5.2.12 on 2026-04-09 18:51

from django.db import migrations


def fix_yoctoproject_cgit_urls(apps, schema_editor):
    """Update git.yoctoproject.org URLs from old cgit paths to new direct paths."""
    LayerItem = apps.get_model('layerindex', 'LayerItem')

    old = 'http://git.yoctoproject.org/cgit/cgit.cgi/'
    new = 'https://git.yoctoproject.org/'

    for layer in LayerItem.objects.filter(vcs_web_url__contains='git.yoctoproject.org/cgit/cgit.cgi/'):
        layer.vcs_web_url = layer.vcs_web_url.replace(old, new)
        layer.vcs_web_tree_base_url = layer.vcs_web_tree_base_url.replace(old, new)
        layer.vcs_web_file_base_url = layer.vcs_web_file_base_url.replace(old, new)
        layer.vcs_web_commit_url = layer.vcs_web_commit_url.replace(old, new)
        layer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0050_alter_recipe_inherits_alter_recipe_license'),
    ]

    operations = [
        migrations.RunPython(fix_yoctoproject_cgit_urls, migrations.RunPython.noop),
    ]
